version: '3.3'

services: 
  server:
    build: .
    environment: 
      WAIT_HOSTS: mongo:27017
    command: python -u server.py
    ports:
      - "80:8000"
    volumes:
      - .:/server
    links:
      - db

  db:
    image: mongo:latest
    hostname: localhost
    environment:
      - MONGO_INITDB_DATABASE=cse312
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017